import json

# Example of how to parse the .jsonl-files generated by GtParser.
# The following loop will go through a log file, and print the ego measurement
# in each time step
with open("2023-11-09_15-24-04/2023-11-09_15-24-04.jsonl", "r") as jsonl_file:
    # For each
    for line in jsonl_file:
        measurements = json.loads(line)
        for measurement in measurements:
            if measurement["ego"]:
                print(measurement)
